import ProductDetailPage from "@/components/ProductDetailPage";

export default function ProductEIPC() {
  return (
    <ProductDetailPage
      badge="IPC Fabric"
      title="EIPC — Embedded Inter-Process Communication"
      subtitle="HMAC-SHA256 · AES-256 · < 1 ms Latency · Multi-Transport"
      description="A capability-secured, authenticated IPC fabric for EoS. Routes messages between tasks, processes, and boards with HMAC-SHA256 integrity, optional AES-256 encryption, and sub-millisecond latency across shared memory, UART, SPI, and TCP transports."
      accent="#F59E0B"
      gradient="from-amber-500/20 to-yellow-600/20"
      lang="C"
      github="embeddedos-org/eipc"
      heroImage="/manus-storage/product-eipc-ipc_be829de0.jpg"
      stackHighlight="ipc fabric"
      stats={[
        { value: "< 1 ms", label: "Cross-Board Latency" },
        { value: "4", label: "Transports (SHM, UART, SPI, TCP)" },
        { value: "HMAC-SHA256", label: "Message Integrity" },
        { value: "AES-256", label: "Optional Encryption" },
      ]}
      workflow={[
        {
          step: 1,
          title: "Define Services and Ports",
          desc: "Each EIPC service is identified by a name and a capability token. Services declare their input and output ports in a manifest file. EoStudio's EIPC Topology Editor can generate this manifest visually.",
          code: "// eipc_manifest.h — generated by EoStudio\n#define EIPC_PORT_SENSOR_OUT   0x0001\n#define EIPC_PORT_AI_IN        0x0002\n#define EIPC_PORT_ACTUATOR_IN  0x0003\n\n// Capability tokens (minted by kernel at boot)\nextern eipc_cap_t cap_sensor;\nextern eipc_cap_t cap_ai;",
        },
        {
          step: 2,
          title: "Open Ports and Connect",
          desc: "Tasks open EIPC ports using their capability tokens. The kernel verifies the capability before granting access. Cross-board connections use the transport layer (UART, SPI, or TCP).",
          code: "// Sensor task opens output port\neipc_port_t out = eipc_port_open(EIPC_PORT_SENSOR_OUT, cap_sensor,\n                                  EIPC_DIR_SEND);\n\n// AI task opens input port\neipc_port_t in  = eipc_port_open(EIPC_PORT_AI_IN, cap_ai,\n                                  EIPC_DIR_RECV);",
        },
        {
          step: 3,
          title: "Send and Receive Messages",
          desc: "Messages are sent with eipc_send() and received with eipc_recv(). The runtime automatically adds HMAC-SHA256 authentication and, if configured, AES-256-GCM encryption.",
          code: '// Sensor task sends a reading\nsensor_data_t data = { .temp = 23.5f, .hum = 60.2f };\neipc_send(out, &data, sizeof(data));\n\n// AI task receives it\nsensor_data_t rx;\neipc_recv(in, &rx, sizeof(rx), EIPC_WAIT_FOREVER);\nprintf("Temp: %.1f  Hum: %.1f\\n", rx.temp, rx.hum);',
        },
        {
          step: 4,
          title: "Cross-Board Communication",
          desc: "For multi-board systems, EIPC transparently routes messages over UART, SPI, or TCP. The sender and receiver use the same eipc_send/recv API regardless of whether the other task is on the same chip or across a network.",
          code: '// Board A: sensor node (UART transport)\neipc_transport_t t = eipc_transport_uart(UART2, 921600);\neipc_port_t remote = eipc_port_connect("board_b/ai_in", t, cap_sensor);\neipc_send(remote, &data, sizeof(data));\n\n// Board B: AI node (receives transparently)\neipc_recv(ai_in_port, &data, sizeof(data), EIPC_WAIT_FOREVER);',
        },
      ]}
      usageExamples={[
        {
          title: "Sensor-to-AI Pipeline",
          scenario:
            "A sensor node sends temperature readings to an AI anomaly detector on the same chip via shared memory EIPC.",
          code: '// Sensor → EIPC (shared memory) → eAI anomaly detector\n#include <eipc/eipc.h>\n\nvoid sensor_task(void *arg) {\n    eipc_port_t out = eipc_port_open(PORT_SENSOR, cap_sensor, EIPC_DIR_SEND);\n    for (;;) {\n        float temp = read_temperature();\n        eipc_send(out, &temp, sizeof(float));\n        eos_task_delay_ms(100);\n    }\n}\n\nvoid ai_task(void *arg) {\n    eipc_port_t in = eipc_port_open(PORT_SENSOR, cap_ai, EIPC_DIR_RECV);\n    eai_model_t anomaly = eai_model_load("anomaly.eai", EAI_BACKEND_CPU);\n    for (;;) {\n        float temp;\n        eipc_recv(in, &temp, sizeof(float), EIPC_WAIT_FOREVER);\n        float score = eai_infer_scalar(anomaly, &temp);\n        if (score > 0.9f) alert_operator();\n    }\n}',
        },
        {
          title: "Multi-Board Robot",
          scenario:
            "A robot with a sensor board (Cortex-M4), an AI board (Cortex-A72), and an actuator board (Cortex-M7) communicating via EIPC over SPI.",
          code: '// Multi-board robot: sensor → AI → actuator via EIPC/SPI\n\n// Sensor board (Cortex-M4)\neipc_transport_t spi_t = eipc_transport_spi(SPI1, 10_MHZ);\neipc_port_t to_ai = eipc_port_connect("ai_board/sensor_in", spi_t, cap);\neipc_send(to_ai, &sensor_frame, sizeof(sensor_frame));\n\n// AI board (Cortex-A72) — receives, infers, forwards\neipc_recv(sensor_in, &frame, sizeof(frame), EIPC_WAIT_FOREVER);\nint cmd = eai_infer_class(nav_model, &frame);\neipc_send(to_actuator, &cmd, sizeof(cmd));\n\n// Actuator board (Cortex-M7) — executes command\neipc_recv(cmd_in, &cmd, sizeof(cmd), EIPC_WAIT_FOREVER);\nmotor_set_velocity(cmd);',
        },
      ]}
      ecosystemRole={{
        importance: "critical",
        role: "Communication Backbone",
        summary:
          "EIPC is the communication backbone of the EoS ecosystem. Every component that needs to talk to another — eNI to eAI, eAI to actuators, eDB to eOffice, EoStudio to EoSim — does so through EIPC. It provides the security guarantees (capability tokens, HMAC integrity, AES encryption) that make multi-component EoS systems trustworthy. Without EIPC, each component would need its own ad-hoc communication protocol, making the system fragile and insecure. EIPC is the glue that turns individual EoS components into a coherent, secure system.",
        dependsOn: [
          "EoS Kernel — EIPC capability tokens are minted and verified by the kernel",
          "EoS IPC primitives — shared memory and message queues underpin the local transport",
          "Hardware UART/SPI/ETH — physical transports for cross-board communication",
        ],
        enabledBy: [
          "eNI → eAI pipeline — neural data flows from acquisition to inference via EIPC",
          "eAI → actuator pipeline — decoded intents reach motors and stimulators via EIPC",
          "eDB — database queries and responses use EIPC for inter-process access",
          "eOffice — all 11 office apps communicate with the EoS platform via EIPC",
          "Multi-board systems — robots, medical devices, and aerospace systems use EIPC cross-board",
        ],
      }}
      features={[
        {
          name: "Capability-Based Security",
          desc: "Every port requires a capability token minted by the EoS kernel. No capability = no access.",
        },
        {
          name: "HMAC-SHA256 Integrity",
          desc: "Every message is authenticated with HMAC-SHA256. Tampered messages are rejected before delivery.",
        },
        {
          name: "AES-256-GCM Encryption",
          desc: "Optional payload encryption for sensitive data (medical, financial, defense).",
        },
        {
          name: "4 Transports",
          desc: "Shared memory (same chip), UART, SPI, and TCP/IP (cross-board). Same API for all.",
        },
        {
          name: "< 1 ms Cross-Board Latency",
          desc: "UART at 921600 baud delivers < 1 ms latency for 64-byte messages.",
        },
        {
          name: "Sequence Numbers",
          desc: "Monotonic sequence numbers detect replay attacks and message reordering.",
        },
        {
          name: "Zero-Copy Shared Memory",
          desc: "On-chip shared memory transport avoids data copies for large payloads (video, audio).",
        },
        {
          name: "Topology Editor",
          desc: "EoStudio's visual EIPC topology editor generates manifests and stub code automatically.",
        },
      ]}
      specs={[
        { key: "Integrity Algorithm", value: "HMAC-SHA256" },
        { key: "Encryption Algorithm", value: "AES-256-GCM (optional)" },
        { key: "Transports", value: "Shared memory, UART, SPI, TCP/IP" },
        {
          key: "Cross-Board Latency (UART)",
          value: "< 1 ms for 64-byte messages at 921600 baud",
        },
        {
          key: "Cross-Board Latency (SPI)",
          value: "< 100 µs for 64-byte messages at 10 MHz",
        },
        {
          key: "Max Message Size",
          value:
            "Configurable; 64 KB default; unlimited with zero-copy shared memory",
        },
        {
          key: "Capability Model",
          value: "Kernel-minted tokens; per-port access control",
        },
        {
          key: "Wire Format",
          value:
            "4-byte magic + version + flags + sequence + header len + payload len + JSON header + payload",
        },
        { key: "License", value: "MIT" },
      ]}
      pairs={[
        {
          name: "EoS Kernel",
          route: "/product-eos",
          desc: "EIPC capability tokens are minted and verified by the EoS kernel security subsystem.",
        },
        {
          name: "eNI",
          route: "/product-eni",
          desc: "Neural data flows from eNI to eAI via EIPC with HMAC integrity and AES encryption.",
        },
        {
          name: "eAI",
          route: "/product-eai",
          desc: "eAI receives sensor data and sends decoded intents to actuators — all via EIPC.",
        },
      ]}
    />
  );
}
