/**
 * eBot's answers, and the matcher that picks one.
 *
 * eBot used to POST every message to `/api/trpc/ebot.chat`, which called an LLM
 * through `forge.manus.im`. Two things were wrong with that in production. The
 * site deploys as a prerendered static build to cPanel — `.cpanel.yml` copies
 * files into the document root and starts no process — so the endpoint answered
 * 404 with the 404 HTML page and the browser reported
 * `Unexpected token '<', "<!DOCTYPE "... is not valid JSON`. Every visitor who
 * opened the chat got "Sorry, I'm having trouble connecting right now."
 * Separately, that host is a sandbox proxy that would not have authenticated
 * from this account even with a server running.
 *
 * So eBot answers from here instead: a fixed set of topics, matched in the
 * browser. No network call, no API key, nothing to expire, and it cannot fail
 * while the page itself is loading.
 *
 * The trade is that eBot only knows what is written here. That is deliberate —
 * every figure below resolves to `shared/stack-data.ts` (regenerated by
 * `pnpm sync:stack` from the source repositories) or to
 * `client/src/data/foundation.ts` (transcribed from the IRS determination), so
 * eBot cannot state a number the rest of the site contradicts. The retired
 * "52+ platforms" figure was still being asserted by the old system prompt long
 * after the pages had moved to the counted figure of 83 boards.
 *
 * When nothing matches, eBot says so and offers the search index rather than
 * guessing. An assistant that invents an answer about medical hardware or
 * charitable status is worse than one that admits the gap.
 */
import { STACK } from "./stack-data";
import { searchSite } from "./site-index";

/** A link eBot can offer alongside an answer. */
export type KnowledgeLink = {
  label: string;
  /** Site route, or an absolute URL for anything off-site. */
  href: string;
};

/** One thing eBot knows how to answer. */
export type Topic = {
  id: string;
  /**
   * Phrases that select this topic. Multi-word phrases score higher than single
   * words, so "get started" beats a passing mention of "start".
   */
  patterns: string[];
  /** The reply, in the small markdown subset `EBot.tsx` renders. */
  answer: string;
  links?: KnowledgeLink[];
};

/** What `answerQuestion` returns. */
export type Answer = {
  reply: string;
  links: KnowledgeLink[];
  /**
   * How the reply was produced. `topic` is a curated answer, `search` is a
   * pointer to matching pages, `unknown` is an admitted gap. Exposed so the UI —
   * and the tests — can tell a real answer from a fallback.
   */
  kind: "topic" | "search" | "unknown";
};

const GITHUB_ORG = "https://github.com/embeddedos-org";

/**
 * The topics, in no particular order — ranking decides which one answers.
 *
 * Keep answers short. This renders in a 360px chat panel, and the markdown
 * subset in `EBot.tsx` supports bold, inline code and line breaks only: no
 * headings, no lists with bullets, no links inside the text (links belong in
 * `links`, which the UI renders as buttons).
 */
export const TOPICS: Topic[] = [
  {
    id: "what-is-embeddedos",
    patterns: [
      "what is embeddedos",
      "what is eos",
      "what does embeddedos do",
      "tell me about embeddedos",
      "about embeddedos",
      "what are you",
      "who are you",
      "what is this site",
      "explain embeddedos",
    ],
    answer:
      `**EmbeddedOS** is an open-source operating system for embedded hardware — from a small microcontroller up to an aircraft flight computer.\n` +
      `\n` +
      `It is built by the Embedded Operating Systems Research Foundation, a 501(c)(3) nonprofit. Everything is released under the **MIT License**: there is no paid tier and no feature held back from the free release.\n` +
      `\n` +
      `The stack is ${STACK.totals.repositories} public repositories covering the kernel, bootloader, IPC, database, build tooling, simulation, on-device AI and an application suite.`,
    links: [
      { label: "What we build", href: "/products" },
      { label: "About the Foundation", href: "/about" },
      { label: "All projects", href: "/projects" },
    ],
  },
  {
    id: "boards",
    patterns: [
      "what boards",
      "which boards",
      "boards supported",
      "supported boards",
      "hardware support",
      "supported hardware",
      "what hardware",
      "which hardware",
      "supported platforms",
      "what platforms",
      "architectures",
      "does it run on",
      "board support",
      "bsp",
      "stm32",
      "esp32",
      "risc-v",
      "cortex",
      "raspberry pi",
      "arduino",
      "nrf",
      "avr",
      "msp430",
    ],
    answer:
      `EmbeddedOS ships **${STACK.totals.boards} board definitions** across **${STACK.totals.architectures} instruction-set architectures**, **${STACK.totals.families} MCU families** and **${STACK.totals.vendors} silicon vendors**.\n` +
      `\n` +
      `That covers ARM Cortex-M and Cortex-A, RISC-V, Xtensa, AVR, MSP430, PIC, MIPS and more. The count comes from the board files in the \`eos\` repository, so it tracks what actually builds.\n` +
      `\n` +
      `No hardware to hand? **EoSim** simulates ${STACK.totals.simulatedPlatforms} platforms, so you can run firmware before you buy a board.`,
    links: [
      { label: "Hardware Lab", href: "/hardware-lab" },
      { label: "Try the simulator", href: "/demo" },
      { label: "Getting started", href: "/getting-started" },
    ],
  },
  {
    id: "getting-started",
    patterns: [
      "how do i get started",
      "get started",
      "getting started",
      "how to start",
      "how do i begin",
      "first steps",
      "install",
      "installation",
      "how to install",
      "set up",
      "setup",
      "quickstart",
      "new to embedded",
      "beginner",
      "tutorial",
      "build my first",
    ],
    answer:
      `Start here — no hardware required.\n` +
      `\n` +
      `**1.** Read the getting-started guide, which walks from an empty machine to running firmware.\n` +
      `**2.** Install the toolchain with \`ebuild\`, the one-command cross-compiler.\n` +
      `**3.** Run your first build against **EoSim** if you have no board yet, or flash it straight to hardware if you do.\n` +
      `\n` +
      `The API reference and the free books cover the stack in depth once you are moving.`,
    links: [
      { label: "Getting started guide", href: "/getting-started" },
      { label: "Documentation", href: "/docs" },
      { label: "Free books", href: "/books" },
      { label: "Downloads", href: "/downloads" },
    ],
  },
  {
    id: "health",
    patterns: [
      "health devices",
      "health device",
      "health hardware",
      "tell me about the health",
      "health key",
      "health band",
      "health ring",
      "health lab",
      "wearable",
      "wearables",
      "biometric",
      "medical device",
      "ecg",
      "spo2",
      "glucose",
      "ehealth365",
      "health monitoring",
    ],
    answer:
      `The Foundation researches four health devices, published openly rather than licensed:\n` +
      `\n` +
      `**HEALTH-KEY ULTRA** — a pocket key with biometric sensing, patent-pending.\n` +
      `**HEALTH-BAND Neuro** — a neural health band using sEMG, patent-pending.\n` +
      `**HEALTH-RING** — a titanium smart ring for continuous monitoring.\n` +
      `**HEALTH-LAB** — a wearable biosensor patch.\n` +
      `\n` +
      `A note that matters: the Foundation does not certify devices for regulatory approval and does not give medical or clinical advice. This is research hardware, not treatment.`,
    links: [
      { label: "Health devices", href: "/health" },
      { label: "Compare the devices", href: "/health-compare" },
      { label: "eHealth365", href: "/ehealth365" },
      { label: "Patents", href: "/patents" },
    ],
  },
  {
    id: "aerospace",
    patterns: [
      "aeroswift",
      "what is aeroswift",
      "aerospace",
      "vtol",
      "air taxi",
      "aircraft",
      "aviation",
      "flight computer",
      "aeros",
      "as-1",
      "as-2",
      "as-10",
      "drone",
    ],
    answer:
      `**AeroSwift** is the Foundation's aerospace research programme, running on AeroOS.\n` +
      `\n` +
      `**AeroSwift Personal (AS-1 / AS-2)** — a personal VTOL aircraft.\n` +
      `**AeroSwift Transit (AS-10)** — a 10-passenger urban air taxi.\n` +
      `\n` +
      `As with the health work, the designs are published so results can be reproduced independently. Airworthiness certification remains the responsibility of whoever brings a vehicle to market.`,
    links: [
      { label: "Aerospace programme", href: "/aerospace" },
      { label: "Research", href: "/research" },
    ],
  },
  {
    id: "license",
    patterns: [
      "license",
      "licence",
      "licensing",
      "mit",
      "open source license",
      "can i use it commercially",
      "commercial use",
      "is it free",
      "cost",
      "how much does it cost",
      "pricing",
      "do i have to pay",
    ],
    answer:
      `Everything is **MIT licensed** and free, including for commercial products. You may read, modify, ship and sell devices running it, with no fee and no separate commercial edition.\n` +
      `\n` +
      `The Foundation is a 501(c)(3) nonprofit and sells no software, licences or access. It is funded by donations.`,
    links: [
      { label: "Licenses", href: "/licenses" },
      { label: "Terms of use", href: "/terms" },
      { label: "Support the work", href: "/donate" },
    ],
  },
  {
    id: "download",
    patterns: [
      "download",
      "downloads",
      "where do i get",
      "source code",
      "github",
      "repository",
      "repositories",
      "clone",
      "releases",
      "binaries",
    ],
    answer: `All ${STACK.totals.repositories} repositories are public on GitHub under the \`embeddedos-org\` organisation, and the downloads page collects tagged releases and source archives in one place.`,
    links: [
      { label: "Downloads", href: "/downloads" },
      { label: "All projects", href: "/projects" },
      { label: "GitHub organisation", href: GITHUB_ORG },
    ],
  },
  {
    id: "contribute",
    patterns: [
      "contribute",
      "contributing",
      "how can i help",
      "get involved",
      "volunteer",
      "pull request",
      "join the project",
      "community",
      "discussions",
      "forum",
      "open source contributor",
    ],
    answer:
      `Contributions go through the public repositories, and technical direction is decided through open governance rather than by any one company.\n` +
      `\n` +
      `Good first steps: read the code of conduct, pick a repository, and introduce yourself in GitHub Discussions. Newcomers get paired with maintainers on real, shipping work.`,
    links: [
      { label: "Get involved", href: "/get-involved" },
      { label: "Community", href: "/community" },
      { label: "Code of conduct", href: "/code-of-conduct" },
      {
        label: "GitHub Discussions",
        href: "https://github.com/orgs/embeddedos-org/discussions",
      },
    ],
  },
  {
    id: "careers",
    patterns: [
      "careers",
      "career",
      "jobs",
      "job",
      "hiring",
      "are you hiring",
      "vacancy",
      "vacancies",
      "apply for a job",
      "work for you",
      "employment",
      "position",
      "openings",
      "internship",
      "intern",
      "fellowship",
      "cpt",
      "opt",
      "resume",
      "cv",
    ],
    answer:
      `The Foundation lists open roles, internships and fellowships on the careers page, including F-1 CPT/OPT and research placements.\n` +
      `\n` +
      `Applications go to **careers@embeddedos.org**. The careers page has a form that prepares the whole application as an email for you, and you can attach a CV to that email before sending.`,
    links: [
      { label: "Open positions", href: "/careers" },
      { label: "Internships & fellowships", href: "/internship" },
      { label: "Email careers@", href: "mailto:careers@embeddedos.org" },
    ],
  },
  {
    id: "donate",
    patterns: [
      "donate",
      "donation",
      "give money",
      "support the foundation",
      "fund",
      "funding",
      "tax deductible",
      "sponsor",
      "sponsorship",
      "membership",
      "501c3",
      "nonprofit status",
      "ein",
    ],
    answer:
      `The Foundation is a **501(c)(3) public charity**, EIN **41-4821627**, and contributions are deductible under IRC Section 170.\n` +
      `\n` +
      `Donations fund the engineering, the free books and the internships. Sponsorship and membership confer recognition, not authority over the roadmap.`,
    links: [
      { label: "Donate", href: "/donate" },
      { label: "Transparency", href: "/transparency" },
      { label: "Membership", href: "/membership" },
      { label: "Partners & sponsors", href: "/partners" },
    ],
  },
  {
    id: "contact",
    patterns: [
      "contact",
      "email",
      "get in touch",
      "reach you",
      "talk to someone",
      "speak to a human",
      "phone",
      "address",
      "where are you based",
      "location",
      "support",
    ],
    answer:
      `Each subject has its own address, and every one reaches a person rather than a queue: **contact@** for general questions, **support@** when you are stuck on the software, **security@** for vulnerabilities, **press@**, **partners@**, **careers@**, **donate@** and **foundation@** for finance.\n` +
      `\n` +
      `The contact page lists all of them along with the Foundation's registered address.`,
    links: [
      { label: "Contact page", href: "/contact" },
      { label: "Email contact@", href: "mailto:contact@embeddedos.org" },
    ],
  },
  {
    id: "security",
    patterns: [
      "security",
      "vulnerability",
      "vulnerabilities",
      "cve",
      "report a bug",
      "disclosure",
      "responsible disclosure",
      "exploit",
      "secure boot",
      "eboot",
      "bootloader",
      "ota",
      "encryption",
    ],
    answer:
      `Report vulnerabilities to **security@embeddedos.org** under the responsible-disclosure policy — not through GitHub issues. Reports are answered within 48 hours.\n` +
      `\n` +
      `On the engineering side, **eBoot** provides secure boot with a hardware root of trust, signed images, A/B OTA updates and anti-rollback protection.`,
    links: [
      { label: "Security policy", href: "/security" },
      { label: "eBoot", href: "/eboot" },
      { label: "Email security@", href: "mailto:security@embeddedos.org" },
    ],
  },
  {
    id: "ai",
    patterns: [
      "eai",
      "edge ai",
      "on-device ai",
      "machine learning",
      "inference",
      "tflite",
      "onnx",
      "llm",
      "eosllm",
      "quantization",
      "neural network",
      "run ai on",
    ],
    answer:
      `**eAI** is the on-device inference layer — TFLite and ONNX models running on the microcontroller itself, with no cloud round trip. **eosllm** runs quantised language models on the same class of hardware.\n` +
      `\n` +
      `**eNI** is the neural-interface framework above it, handling EEG, ECoG, sEMG and spike-sorting pipelines.`,
    links: [
      { label: "eAI", href: "/eai" },
      { label: "eAI Edge stack", href: "/eai-edge" },
      { label: "eNI neural interface", href: "/eni" },
    ],
  },
  {
    id: "simulator",
    patterns: [
      "eosim",
      "simulator",
      "simulate",
      "emulator",
      "emulate",
      "virtual board",
      "no hardware",
      "without a board",
      "test without hardware",
      "demo",
    ],
    answer:
      `**EoSim** simulates ${STACK.totals.simulatedPlatforms} platforms, so you can write, run and debug firmware without owning the board. GPIO, UART, SPI and I²C all behave as they would on hardware.\n` +
      `\n` +
      `There is a live simulator on the demo page — nothing to install.`,
    links: [
      { label: "Live demo", href: "/demo" },
      { label: "Hardware Lab", href: "/hardware-lab" },
    ],
  },
  {
    id: "apps",
    patterns: [
      "eapps",
      "eoffice",
      "applications",
      "app store",
      "ebrowser",
      "edb",
      "database",
      "office suite",
      "spreadsheet",
      "word processor",
      "eosuite",
    ],
    answer: `**eApps** is the application layer: the **eOffice** suite, **eBrowser** (an embedded web engine), **eDB** (an embedded database with AES-256 at-rest encryption) and the rest of the system and media apps.`,
    links: [
      { label: "eApps store", href: "/eapps" },
      { label: "eOffice suite", href: "/eoffice" },
      { label: "eBrowser", href: "/ebrowser" },
      { label: "eDB", href: "/edb" },
    ],
  },
  {
    id: "docs",
    patterns: [
      "documentation",
      "docs",
      "api reference",
      "api docs",
      "manual",
      "guide",
      "reference",
      "books",
      "learn",
      "course",
      "training",
      "certification",
    ],
    answer:
      `Documentation, the C API reference and the full-length technical books are all free — publishing the teaching material that embedded engineering usually keeps behind paid training is one of the Foundation's charitable programmes.\n` +
      `\n` +
      `There is also a Kids Edition, and certification at no cost to the candidate.`,
    links: [
      { label: "Documentation", href: "/docs" },
      { label: "API reference", href: "/api-docs" },
      { label: "Books", href: "/books" },
      { label: "Kids Edition", href: "/kids" },
    ],
  },
  {
    id: "roadmap",
    patterns: [
      "roadmap",
      "future",
      "upcoming",
      "next release",
      "when will",
      "planned",
      "release schedule",
      "changelog",
      "what is new",
      "latest release",
    ],
    answer: `The roadmap page carries the planned milestones, and the changelog records what has already shipped. Performance work is stated there as targets rather than as measured figures, because the repositories carry no published benchmark to cite yet.`,
    links: [
      { label: "Roadmap", href: "/roadmap" },
      { label: "Changelog", href: "/changelog" },
      { label: "News", href: "/news" },
    ],
  },
];

/**
 * Score one topic against a normalised question.
 *
 * A multi-word pattern is worth far more than a single word, because a phrase
 * hit ("get started") is strong evidence of intent while a bare word ("start")
 * often appears by accident. Word-boundary matching keeps "ai" out of "chair"
 * and "opt" out of "option".
 */
const scoreTopic = (topic: Topic, q: string): number => {
  let score = 0;
  for (const pattern of topic.patterns) {
    if (pattern.includes(" ")) {
      if (q.includes(pattern)) score += 10 + pattern.length / 10;
    } else if (new RegExp(`\\b${escapeRegExp(pattern)}\\b`).test(q)) {
      score += 3;
    }
  }
  return score;
};

/** Escape a pattern for literal use inside a RegExp. */
const escapeRegExp = (s: string): string =>
  s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Strip punctuation and collapse whitespace so patterns match plain prose.
 *
 * Removes a known punctuation set rather than keeping a known letter set: the
 * project compiles without an explicit `target`, so the unicode-property regex
 * flag needed for `\p{L}` is unavailable, and an ASCII-only whitelist would
 * shred accented words into fragments. Hyphens survive because board and
 * product names contain them ("risc-v", "health-ring", "as-10").
 */
const normalise = (question: string): string =>
  question
    .toLowerCase()
    .replace(/[.,/#!$%^&*;:{}=~()?"'`|<>+[\]\\@_‘’“”]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

/** Below this, a topic match is too weak to be worth asserting. */
const MIN_TOPIC_SCORE = 3;

/**
 * Below this, a search hit is not worth offering as a suggestion.
 *
 * `scoreItem` awards a point for a bare substring overlap in either direction,
 * which is generous enough for a search box the visitor is watching but wrong
 * here: "what is the airspeed velocity of a swallow" scores against the tag
 * "ai" because "airspeed" contains it, and eBot would answer an unanswerable
 * question with a confident-looking link to the edge-AI page. Requiring more
 * than one incidental overlap keeps the fallback honest.
 */
const MIN_SEARCH_SCORE = 3;

/** Greetings get a greeting, not a search result for the word "hello". */
const GREETINGS =
  /^(hi|hey|hello|yo|howdy|greetings|good (morning|afternoon|evening)|thanks|thank you|ty|cheers|bye|goodbye)\b/;

/**
 * Answer a visitor's question from the knowledge base.
 *
 * Tries the curated topics first. Failing that, falls back to the site search
 * index so a question about any page still gets a useful pointer. Failing that
 * too, says plainly that it does not know — it never invents an answer.
 *
 * @param question Raw text as typed. Case and punctuation do not matter.
 * @returns The reply, any links to offer, and which of the three routes produced it.
 *
 * @example
 * answerQuestion("What boards does EmbeddedOS support?").kind;  // "topic"
 * answerQuestion("tell me about quantum computing").kind;       // "search"
 * answerQuestion("what is the airspeed of a swallow").kind;     // "unknown"
 */
export function answerQuestion(question: string): Answer {
  const q = normalise(question);

  if (!q) {
    return {
      reply:
        "Ask me anything about EmbeddedOS — the hardware it runs on, how to get started, or what the Foundation does.",
      links: [],
      kind: "unknown",
    };
  }

  if (GREETINGS.test(q) && q.split(" ").length <= 4) {
    return {
      reply:
        "Hello! Ask me about supported hardware, getting started, the health or aerospace research, licensing, or how to contribute.",
      links: [
        { label: "Getting started", href: "/getting-started" },
        { label: "What we build", href: "/products" },
      ],
      kind: "topic",
    };
  }

  const ranked = TOPICS.map(topic => ({ topic, score: scoreTopic(topic, q) }))
    .filter(t => t.score >= MIN_TOPIC_SCORE)
    .sort((a, b) => b.score - a.score);

  if (ranked.length > 0) {
    const { topic } = ranked[0];
    return { reply: topic.answer, links: topic.links ?? [], kind: "topic" };
  }

  // Nothing curated matched. The search index covers every page on the site, so
  // it can still point somewhere useful without asserting anything new.
  const { pages } = searchSite(question);
  const confident = pages.filter(p => p.score >= MIN_SEARCH_SCORE);
  if (confident.length > 0) {
    const top = confident.slice(0, 3);
    return {
      reply: `I don't have a prepared answer for that, but ${top.length === 1 ? "this page looks" : "these pages look"} relevant:`,
      links: top.map(p => ({ label: p.title, href: p.path })),
      kind: "search",
    };
  }

  return {
    reply:
      "I don't know that one — I only know what's published on this site, and I'd rather say so than guess.\n" +
      "\n" +
      "Try rephrasing, or email **contact@embeddedos.org** and a person will answer.",
    links: [
      { label: "FAQ", href: "/faq" },
      { label: "Documentation", href: "/docs" },
      { label: "Email contact@", href: "mailto:contact@embeddedos.org" },
    ],
    kind: "unknown",
  };
}
